/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import estructuras.*;
/**
 *
 * @author Alessandra
 */
public class Vent_Principal extends javax.swing.JFrame {
    Lista_Circular lista_jugadores = new Lista_Circular();
    Cola colaFicha =  new Cola();
    public Vent_Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Matriz = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));

        Panel_Matriz.setMaximumSize(new java.awt.Dimension(540, 540));
        Panel_Matriz.setMinimumSize(new java.awt.Dimension(540, 540));
        Panel_Matriz.setPreferredSize(new java.awt.Dimension(540, 540));

        javax.swing.GroupLayout Panel_MatrizLayout = new javax.swing.GroupLayout(Panel_Matriz);
        Panel_Matriz.setLayout(Panel_MatrizLayout);
        Panel_MatrizLayout.setHorizontalGroup(
            Panel_MatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        Panel_MatrizLayout.setVerticalGroup(
            Panel_MatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_Matriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Matriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel_Matriz;
    // End of variables declaration//GEN-END:variables

public void ingresoJugador(String nombre){
    this.lista_jugadores.Agregar_Jugador(nombre);
    //this.lista_jugadores.Imprimir();
}

public void imprimirLista(){
    this.lista_jugadores.graficar_Jugador();
}

public void cargarFichas_Cola(String Letra){
    this.colaFicha.enColar(Letra);
}

public void random_Letra(){
    //String[] abecedario ={"A","B","C","D","E","F","G","H","I","J","L","M","N","Ñ","O","P","Q","R","S","T","U","V","X","Y","Z"};
    Lista_Letras list =  new Lista_Letras();
    int numero;
    int cantidad;
    list.ingresar(1,"A", 12);
    list.ingresar(2,"B", 2);
    list.ingresar(3,"C", 4);
    list.ingresar(4,"D", 5);
    list.ingresar(5,"E", 12);
    list.ingresar(6,"F", 1);
    list.ingresar(7,"G", 2);
    list.ingresar(8,"H", 2);
    list.ingresar(9,"I", 6);
    list.ingresar(10,"J", 1);
    list.ingresar(11,"L", 4);
    list.ingresar(12,"M", 2);
    list.ingresar(13,"N", 5);
    list.ingresar(14,"Ñ", 1);
    list.ingresar(15,"O", 9);
    list.ingresar(16,"P", 2);
    list.ingresar(17,"Q", 1);
    list.ingresar(18,"R", 5);
    list.ingresar(19,"S", 6);
    list.ingresar(20,"T", 4);
    list.ingresar(21,"U", 5);
    list.ingresar(22,"V", 1);
    list.ingresar(23,"X", 1);
    list.ingresar(24,"Y", 1);
    list.ingresar(25,"Z", 1);

    while(!list.esVacia()){
    numero = (int)(Math.random()*25)+1;
    cantidad = list.buscar_cantidad(numero);
    
    if(cantidad>0){
    this.cargarFichas_Cola(list.buscar_letra(numero));
    list.modificar_valor(numero, cantidad-1);
    }else{
        list.Eliminar(numero);
    }
    }
            
    
}





}
